### ISSUE TITLE
Problème nom de catégorie

### ISSUE THREAD

**Issue by youssef-t** [jolignier/face-mask-dataset-ilc-2021#16]
Certaines annotations ont comme catégorie "mask_weared_incorrect" au lieu de "with_incorrect_mask".

Exemple: le fichier "annotations/0294a2bd4e2f4641e050176d83134542.xml"

**Comment by Mortpo** [comment]
C'est PN

**Comment by jolignier** [comment]
Wallah c'était PNC (exemple -> ec8a45ab03c4a4dd623c30f3f4d47ee4.xml)
C'est fixé
